In [2]:
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score, accuracy_score
import pandas as pd 
import joblib

In [12]:
df = pd.read_csv('Data/Housing.csv')
le = LabelEncoder()
scaler = StandardScaler()
df.mainroad = le.fit_transform(df.mainroad)
df.guestroom = le.fit_transform(df.guestroom)
df.basement =  le.fit_transform(df.basement)
df.hotwaterheating = le.fit_transform(df.hotwaterheating)
df.airconditioning =  le.fit_transform(df.airconditioning)
df.prefarea =  le.fit_transform(df.prefarea)
df.furnishingstatus = le.fit_transform(df.furnishingstatus)

# df[['price']] = scaler.fit_transform(df[['price']])
x = df.drop(columns=['price' ], axis=1)
y = df['price']

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)
x

,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,7420,4,2,3,1,0,0,0,1,2,1,0
1,8960,4,4,4,1,0,0,0,1,3,0,0
2,9960,3,2,2,1,0,1,0,0,2,1,1
3,7500,4,2,2,1,0,1,0,1,3,1,0
4,7420,4,1,2,1,1,1,0,1,2,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
540,3000,2,1,1,1,0,1,0,0,2,0,2
541,2400,3,1,1,0,0,0,0,0,0,0,1
542,3620,2,1,1,1,0,0,0,0,0,0,2
543,2910,3,1,1,0,0,0,0,0,0,0,0
544,3850,3,1,2,1,0,0,0,0,0,0,2

In [16]:
model = LinearRegression()
model.fit(x_train, y_train)

y_pred =  model.predict(x_test)
r2 = r2_score(y_test, y_pred)
mse =  mean_squared_error(y_test, y_pred)
y_pred


joblib.dump(model, 'models/housing.joblib')

['models/housing.joblib']

In [87]:
model = KNeighborsRegressor()
model.fit(x_train, y_train)
y_pred = model.predict(x_test)
r2 = r2_score(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)

In [88]:
model = RandomForestRegressor(n_estimators=100, random_state=42)
model.fit(x_train, y_train)
y_pred = model.predict(x_test)
r2 = r2_score(y_test, y_pred)